# column transformer

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df = pd.read_csv('tested.csv')

In [10]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,0,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
6,898,1,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,0,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
9,901,0,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,NaN,S

In [22]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [11]:
df.shape

(418, 12)

In [6]:
from sklearn.compose import ColumnTransformer

In [25]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['Fare']),
    ('tnf2',OneHotEncoder(drop = 'first'),['Sex','Embarked'])
],remainder = 'passthrough')

In [26]:
transformer.fit(df)
df_transformed =transformer.transform(df)
df_transformed

array([[7.8292, 1.0, 1.0, ..., 0, '330911', nan],
       [7.0, 0.0, 0.0, ..., 0, '363272', nan],
       [9.6875, 1.0, 1.0, ..., 0, '240276', nan],
       ...,
       [7.25, 1.0, 0.0, ..., 0, 'SOTON/O.Q. 3101262', nan],
       [8.05, 1.0, 0.0, ..., 0, '359309', nan],
       [22.3583, 1.0, 0.0, ..., 1, '2668', nan]],
      shape=(418, 13), dtype=object)

In [34]:
df_new = pd.DataFrame(df_transformed)
df_new

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,7.8292,1.0,1.0,0.0,892,0,3,"Kelly, Mr. James",34.5,0,0,330911,NaN
1,7.0,0.0,0.0,1.0,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",47.0,1,0,363272,NaN
2,9.6875,1.0,1.0,0.0,894,0,2,"Myles, Mr. Thomas Francis",62.0,0,0,240276,NaN
3,8.6625,1.0,0.0,1.0,895,0,3,"Wirz, Mr. Albert",27.0,0,0,315154,NaN
4,12.2875,0.0,0.0,1.0,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",22.0,1,1,3101298,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,8.05,1.0,0.0,1.0,1305,0,3,"Spector, Mr. Woolf",NaN,0,0,A.5. 3236,NaN
414,108.9,0.0,0.0,0.0,1306,1,1,"Oliva y Ocana, Dona. Fermina",39.0,0,0,PC 17758,C105
415,7.25,1.0,0.0,1.0,1307,0,3,"Saether, Mr. Simon Sivertsen",38.5,0,0,SOTON/O.Q. 3101262,NaN
416,8.05,1.0,0.0,1.0,1308,0,3,"Ware, Mr. Frederick",NaN,0,0,359309,NaN
417,22.3583,1.0,0.0,0.0,1309,0,3,"Peter, Master. Michael J",NaN,1,1,2668,NaN

In [31]:
df_new.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket          86
Fare             0
Cabin            0
Embarked         0
extra          327
dtype: int64